ALTER TABLE users
  ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50) UNIQUE NULL AFTER email,
  MODIFY COLUMN password_hash VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS otp_code VARCHAR(10) NULL AFTER phone_number,
  ADD COLUMN IF NOT EXISTS otp_expires_at DATETIME NULL AFTER otp_code;
