ALTER TABLE kids
  ADD COLUMN date_of_birth VARCHAR(20) NULL AFTER age,
  ADD COLUMN gender VARCHAR(30) NULL AFTER date_of_birth,
  ADD COLUMN home_location VARCHAR(255) NULL AFTER grade,
  ADD COLUMN home_lat DECIMAL(10, 8) NULL AFTER home_location,
  ADD COLUMN home_lng DECIMAL(11, 8) NULL AFTER home_lat,
  ADD COLUMN school_location VARCHAR(255) NULL AFTER home_lng,
  ADD COLUMN school_lat DECIMAL(10, 8) NULL AFTER school_location,
  ADD COLUMN school_lng DECIMAL(11, 8) NULL AFTER school_lat,
  ADD COLUMN morning_pickup_time VARCHAR(20) NULL AFTER school_lng,
  ADD COLUMN afternoon_return_time VARCHAR(20) NULL AFTER morning_pickup_time,
  ADD COLUMN pickup_notes TEXT NULL AFTER afternoon_return_time,
  ADD COLUMN emergency_contact_name VARCHAR(255) NULL AFTER pickup_notes,
  ADD COLUMN emergency_contact_relationship VARCHAR(100) NULL AFTER emergency_contact_name,
  ADD COLUMN emergency_contact_phone VARCHAR(50) NULL AFTER emergency_contact_relationship,
  ADD COLUMN guardian_name VARCHAR(255) NULL AFTER emergency_contact_phone,
  ADD COLUMN guardian_relationship VARCHAR(100) NULL AFTER guardian_name,
  ADD COLUMN guardian_phone VARCHAR(50) NULL AFTER guardian_relationship,
  ADD COLUMN allow_live_tracking BOOLEAN DEFAULT TRUE AFTER guardian_phone,
  ADD COLUMN safety_consent_at TIMESTAMP NULL AFTER allow_live_tracking;