ALTER TABLE riders
  MODIFY COLUMN parent_user_id INT NULL,
  MODIFY COLUMN school VARCHAR(255) NULL,
  MODIFY COLUMN grade VARCHAR(50) NULL,
  ADD COLUMN full_name VARCHAR(255) NULL AFTER user_id,
  ADD COLUMN date_of_birth VARCHAR(20) NULL AFTER full_name,
  ADD COLUMN nationality VARCHAR(100) NULL AFTER date_of_birth,
  ADD COLUMN national_id_number VARCHAR(100) NULL AFTER nationality,
  ADD COLUMN residential_area VARCHAR(255) NULL AFTER national_id_number,
  ADD COLUMN stage_association VARCHAR(255) NULL AFTER residential_area,
  ADD COLUMN driving_licence_number VARCHAR(100) NULL AFTER stage_association,
  ADD COLUMN permit_number VARCHAR(100) NULL AFTER driving_licence_number,
  ADD COLUMN licence_expiry_date VARCHAR(20) NULL AFTER permit_number,
  ADD COLUMN years_of_riding INT NULL AFTER licence_expiry_date,
  ADD COLUMN authorised_vehicle_class VARCHAR(100) NULL AFTER years_of_riding,
  ADD COLUMN vehicle_type ENUM('boda', 'tuktuk') NULL AFTER authorised_vehicle_class,
  ADD COLUMN number_plate VARCHAR(50) NULL AFTER vehicle_type,
  ADD COLUMN ownership_status VARCHAR(100) NULL AFTER number_plate,
  ADD COLUMN insurance_info VARCHAR(255) NULL AFTER ownership_status,
  ADD COLUMN insurance_expiry_date VARCHAR(20) NULL AFTER insurance_info,
  ADD COLUMN verification_consent_accepted BOOLEAN DEFAULT FALSE AFTER insurance_expiry_date,
  ADD COLUMN training_accepted BOOLEAN DEFAULT FALSE AFTER verification_consent_accepted,
  ADD COLUMN safeguarding_accepted BOOLEAN DEFAULT FALSE AFTER training_accepted,
  ADD COLUMN approval_status ENUM('draft', 'pending_review', 'approved', 'rejected', 'suspended') DEFAULT 'draft' AFTER safeguarding_accepted,
  ADD COLUMN submitted_at TIMESTAMP NULL AFTER approval_status;
